### PR TITLE
Add LDAP authentication backend

### PR DESCRIPTION
**Pull request by nebulade**
Hi, this pull request is not meant to get merged at the moment. I just use this to see if this is useful to get upstream in the first place. 

The LDAP auth backend is meant for the https://cloudron.io app, on which I am working at.

So far it is functional during my rudimentary testing. 

Currently this still depends on user records in the users db table, to have a place to store the API accessToken. LDAP user records are inserted with an empty password. Not sure if that is the way to go here. Also the admin record is inserted by `mailtrain.sql` which might not be the best idea when only using LDAP auth.

Additionally I am working on disabling the UI bits for password reset and change.

Would be great to get some feedback and also get to know if this even has any chance to get upstreamed.

Thanks for the great application already! :-)

### CODE REVIEW

**Comment by andris9** [comment]
Awesome idea!

The password mismatch between LDAP and local should not be an issue as the password from the database is not checked when performing LDAP auth, so the PR seems quite OK as it already is.

Maybe also add a check to the local auth so that an empty password could not be used. This would prevent the situation where you disable LDAP for whatever reason and now everybody can sign in using a blank password.

**Comment by nebulade** [comment]
Good idea, will update the pull request in a bit. Just working through the html templates to hide the non relevant parts, when using LDAP

**Comment by nebulade** [comment]
I have now added an additional config variable to specify the password reset link, so users can proceed to the LDAP management UI

**Comment by andris9** [comment]
Great! I'll set up a local LDAP server later today and try it out

**Comment by gramakri** [comment]
@andris9 did you get a chance to try it out?

**Comment by nebulade** [comment]
Is there anything I can help with getting test done for this feature?

**Comment by andris9** [comment]
Actually I did not manage to get it working. Could you provide a sample server script (probably using ldapjs) as well that can be used as test auth backend?

Something like this:

```
node test-ldap-server.js &
node index.js
```

**Comment by nebulade** [comment]
Yeah LDAP can  be quite tricky to start with. I quickly built an ldapjs based one and it's now at https://github.com/nebulade/ldapjstestserver
```
npm install
./index.js
```
It just has two hardcoded user records, which it prints out, very basic code.
Should hopefully work with the configuration bits in mailtrain would look like:
```
[ldap]
# enable to use ldap user backend
enabled=true
host="localhost"
port=3002
baseDN="ou=users,dc=example"
filter="(|(username={{username}})(mail={{username}}))"
passwordresetlink="http://example.com"
```

**Comment by andris9** [comment]
Thanks, I'll check it out in a day or two

**Pull request merged**
