### PR TITLE
[bugfix] Fix LDAP issue with OpenLDAP/MS AD

### PR DESCRIPTION
**Pull request by larrabee**
LDAP not worked if "username" field not present. I was add new parameter to config to change username field name if needed.

### CODE REVIEW

**Comment by andris9** [comment]
Maybe @nebulade can review this? I don't know much about LDAP.

**Comment by nebulade** [comment]
I will look into it. Already now I can tell that the `package.json` should not include the ldapjs passport module. At least I had it initially also included in my first PR, which was correctly mentioned to not be needed.

**Comment by larrabee** [comment]
Hello. Without passport-ldapjs module auth fails with error "Unknown auth type LDAP".

**Comment by nebulade** [comment]
I think the intention was that if you configure to use ldap then you manually install that module. But since most people don't use it, no need to pull in the dependency by default. Maybe @andris9 can give his opinion on that as well.

**Comment by nebulade** [comment]
The change otherwise looks good. Maybe I can research a bit if there is a common pattern at other popular project's ldap integration to name the username field `uidTag`

**Comment by andris9** [comment]
@nebulade thanks! I did not want to blindly accept this as it might have caused issues with existing LDAP users.

The problem with passport-ldapjs was that it includes a compiled dependency (dtrace_provider) that might not work everywhere. It seems though that it is an optional dependency, not a strict requirement, so I guess that it would be OK to include passport-ldapjs in Mailtrain dependencies – in worst case you get a long list of compilation errors but it should not break the Mailtrain installation process.

**Comment by larrabee** [comment]
Ok, that about [this](https://github.com/andris9/mailtrain/pull/178/commits/1ca27b6b404e6e4be181be846c5a97dc9e61b190)?

**Comment by andris9** [comment]
@larrabee I think that the warning should be shown only if the LDAP authentication is actually enabled. You can check it from `config.ldap.enabled`.

Instead of `console.warn` use the included log module:

    log.info('LDAP', 'Module "passport-ldapjs" not installed. LDAP auth will fail.');

**Comment by andris9** [comment]
Thanks!

**Comment by larrabee** [comment]
Thank you ;)

**Comment by nebulade** [comment]
Great to see more usage of the ldap part! I only really put in just enough effort to get it working well on Cloudron, instead of making it very generic, like it is now a bit more.

**Pull request merged**
